sonar.projectKey=engsoftwareII2025.2
sonar.organization=jonatas
sonar.sources=TESTES-ETAPAFINAL/service_tag_manager
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml