name: SonarCloud

on:
  push:
    branches:
      - principal
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependências
        run: |
          pip install pytest pytest-cov PyQt5 ruff pyright PyQt5-stubs

      - name: Rodar testes
        run: |
          pytest TESTES-ETAPAFINAL/tests --cov=TESTES-ETAPAFINAL/service_tag_manager --cov-report=xml:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}